/**
 * @file openai-chat.service.ts
 * @description Provider service that communicates with the OpenAI API to evaluate user messages using a system prompt.
 * Encapsulates all interaction logic with the OpenAI LLM.
 */

import { env } from '@config/env/env.config';
import {
    Injectable,
    InternalServerErrorException,
    Logger,
} from '@nestjs/common';
import OpenAI from 'openai';

@Injectable()
export class OpenAiChatService {
    private readonly logger = new Logger(OpenAiChatService.name);
    private readonly client = new OpenAI({ apiKey: env.OPENAI_API_KEY });
    private readonly model = env.LLM_MODEL || 'gpt-3.5-turbo';
    private readonly temperature = 0.2;

    /**
     * Sends a system prompt to the OpenAI Chat API and returns the model's raw textual response.
     * @param systemPrompt - The prompt that defines the system's behavior and user input.
     * @returns The raw content generated by the OpenAI model.
     * @throws InternalServerErrorException if the communication with OpenAI fails.
     */
    async chat(systemPrompt: string): Promise<string> {
        try {
            const res = await this.client.chat.completions.create({
                model: this.model,
                messages: [
                    {
                        role: 'system',
                        content: systemPrompt,
                    },
                ],
                temperature: this.temperature,
            });

            return res.choices[0]?.message?.content ?? '';
        } catch (err) {
            this.logger.error(
                'Error communicating with OpenAI',
                err instanceof Error ? err.stack : '',
            );
            throw new InternalServerErrorException(
                'Error communicating with OpenAI.',
            );
        }
    }
}
